package dump

import (
	"bytes"
	"context"
	"strings"
	"testing"

	"github.com/uptrace/bun"
)

func TestWriteHeader(t *testing.T) {
	var b strings.Builder
	if err := writeHeader(&b, "test/e2e/dump.yaml"); err != nil {
		t.Fatal(err)
	}

	t.Run("disables triggers and FK checks inside one transaction", func(t *testing.T) {
		want := `-- Code generated by bungen dump from test/e2e/dump.yaml. DO NOT EDIT.
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET TimeZone = 'UTC';
SET session_replication_role = replica;
BEGIN;

`
		if b.String() != want {
			t.Errorf("header =\n%s\nwant\n%s", b.String(), want)
		}
	})
}

func TestRenderSetval(t *testing.T) {
	tables := map[string]*table{
		"public.person":     {Schema: "public", Name: "person"},
		"public.person_acq": {Schema: "public", Name: "person_acq"},
	}

	t.Run("one GREATEST over every table using the sequence", func(t *testing.T) {
		s := sequence{Name: "public.person_id_seq", Uses: []sequenceUse{{"public.person", "id"}, {"public.person_acq", "id"}}}
		want := `SELECT setval('public.person_id_seq', GREATEST(1, (SELECT max("id") FROM ONLY "public"."person"), (SELECT max("id") FROM ONLY "public"."person_acq")));`
		if got := renderSetval(s, tables); got != want {
			t.Errorf("renderSetval =\n%s\nwant\n%s", got, want)
		}
	})

	t.Run("quotes the sequence name as a literal", func(t *testing.T) {
		s := sequence{Name: `public."it's"`, Uses: []sequenceUse{{"public.person", "id"}}}
		if got := renderSetval(s, tables); !strings.HasPrefix(got, `SELECT setval('public."it''s"', `) {
			t.Errorf("renderSetval = %s", got)
		}
	})
}

func TestUsedBy(t *testing.T) {
	s := sequence{Name: "public.person_id_seq", Uses: []sequenceUse{{"public.person", "id"}, {"public.person_acq", "id"}}}

	t.Run("true when one of its tables has rows", func(t *testing.T) {
		rows := rowSet{}
		rows.add("public.person_acq", []string{"(0,1)"})
		if !usedBy(s, rows) {
			t.Error("usedBy = false")
		}
	})

	t.Run("false when none of its tables has rows", func(t *testing.T) {
		if usedBy(s, rowSet{}) {
			t.Error("usedBy = true")
		}
	})
}

func TestWriteData(t *testing.T) {
	db, _ := newDB(t, fixtureSchema, fixtureData)
	cfg := mustConfig(t, "seeds:\n  - table: status\n    child_depth: 0\n")
	ctx := context.Background()

	var out bytes.Buffer
	err := withSnapshot(ctx, db, func(conn bun.Conn) error {
		cat, err := loadCatalog(ctx, conn.Conn)
		if err != nil {
			return err
		}
		rows, err := walk(ctx, conn.Conn, cat, cfg)
		if err != nil {
			return err
		}
		return writeData(ctx, conn, &out, cat, rows, "test.yaml")
	})
	if err != nil {
		t.Fatalf("writeData: %v", err)
	}

	t.Run("writes a COPY block per table, then the setvals", func(t *testing.T) {
		var want strings.Builder
		if err := writeHeader(&want, "test.yaml"); err != nil {
			t.Fatal(err)
		}
		want.WriteString("COPY \"public\".\"status\" (\"id\", \"code\") FROM stdin;\n" +
			"1\tnew\n2\topen\n3\twon\n4\tlost\n" +
			"\\.\n\n" +
			"SELECT setval('public.status_id_seq', GREATEST(1, (SELECT max(\"id\") FROM ONLY \"public\".\"status\")));\n" +
			"\nCOMMIT;\n")
		if out.String() != want.String() {
			t.Errorf("script =\n%s\nwant\n%s", out.String(), want.String())
		}
	})
}
