package dump

import (
	"context"
	"fmt"
	"io"
	"slices"
	"strings"

	"github.com/uptrace/bun"
	"github.com/uptrace/bun/driver/pgdriver"
)

// writeHeader starts the script: one transaction in which user triggers and FK
// checks are off (session_replication_role needs a superuser), so table order
// and FK cycles do not matter and no trigger rewrites the data.
func writeHeader(w io.Writer, source string) error {
	_, err := fmt.Fprintf(w, `-- Code generated by bungen dump from %s. DO NOT EDIT.
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET TimeZone = 'UTC';
SET session_replication_role = replica;
BEGIN;

`, source)
	return err
}

// maxExpr is the highest value any column drawing from s holds once loaded,
// at least 1. GREATEST ignores the NULL max of an empty table.
func maxExpr(s sequence, tables map[string]*table) string {
	parts := []string{"1"}
	for _, u := range s.Uses {
		parts = append(parts, fmt.Sprintf("(SELECT max(%s) FROM ONLY %s)", quoteIdent(u.Column), tables[u.Table].qualified()))
	}
	return "GREATEST(" + strings.Join(parts, ", ") + ")"
}

// renderSetval moves s past every loaded value, computed at load time, so a
// test's first insert does not collide with a loaded row.
func renderSetval(s sequence, tables map[string]*table) string {
	return fmt.Sprintf("SELECT setval(%s, %s);", quoteLiteral(s.Name), maxExpr(s, tables))
}

// usedBy reports whether a table drawing from s has selected rows.
func usedBy(s sequence, rows rowSet) bool {
	return slices.ContainsFunc(s.Uses, func(u sequenceUse) bool { return len(rows[u.Table]) > 0 })
}

// writeData writes the psql script loading rows: the header, a COPY block per
// table with rows, a setval per sequence those tables use, and COMMIT.
func writeData(ctx context.Context, conn bun.Conn, w io.Writer, cat *catalog, rows rowSet, source string) error {
	if err := writeHeader(w, source); err != nil {
		return err
	}

	for _, key := range cat.Keys {
		ctids := rows.sorted(key)
		if len(ctids) == 0 {
			continue
		}
		t := cat.Tables[key]
		if _, err := fmt.Fprintln(w, copyHeader(t)); err != nil {
			return err
		}
		if _, err := pgdriver.CopyTo(ctx, conn, w, copySQL(t), tidArray(ctids)); err != nil {
			return fmt.Errorf("dump: copy %s: %w", key, err)
		}
		if _, err := io.WriteString(w, "\\.\n\n"); err != nil {
			return err
		}
	}

	for _, s := range cat.Sequences {
		if !usedBy(s, rows) {
			continue
		}
		if _, err := fmt.Fprintln(w, renderSetval(s, cat.Tables)); err != nil {
			return err
		}
	}

	_, err := io.WriteString(w, "\nCOMMIT;\n")
	return err
}
